<a href="https://colab.research.google.com/github/mcd-unison/material-programacion/blob/main/intro-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>


# Curso Propedéutico en *Programación*

# Introducción a `pandas`


**Julio Waissman Vilanova**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl

## Creando un dataframe

Pandas es un marco de desarrollo para la manipulación de datos, creado originalmente para ofrecer en python las facilidades de manejo de tablas de datos que tiene en forma nativa el lenguaje `R`.

Pandas se basa en dos clases: `Serie` y `DataFrame`, ambas heredadas de la clase `ndarray`de numpy. Un objeto de la clase `Serie`(que llamaremos serie) es un arreglo de datos de un solo tipo, los cuales se encuentran indexados. Un objeto tipo `DataFrame`es una colección de series, en la que se comparte el índice (o renglón), pero cada serie (o columna) tiene su propio tipo. En la figura se muestra como es un DataFrame

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg)

Vamos a crear un `Dataframe`:

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"]
    }
)

In [23]:
import pandas as pd # Import the pandas library

df = pd.DataFrame(
    {
        "Name": [
            "Velazquez, Miss. Diana Laura",
            "Tan, Mr. Aldo Garcia",
            "Ochoa, Miss. Rebecca",
            "Rangel, Miss. Edith",
            "padilla, Miss. Paulina",
        ],
    "Age": [22, 25, 23, 23,24],
        "sex":["Female", "Male", "Female","Female", "Female"]}
)

Y vamos a ver los primeros 2 elementos y los últomos 3

In [24]:
display(df.head(2))

                           Name  Age     sex
0  Velazquez, Miss. Diana Laura   22  Female
1          Tan, Mr. Aldo Garcia   25    Male

In [20]:
display(df.tail(2))

                     Name  age     sex
3     Rangel, Miss. Edith   23  Female
4  padilla, Miss. Paulina   24  Female

Ahora vamos a investigar la información de la tabla y cada una de las series que la componen:

In [21]:
df['Name']

0    Velazquez, Miss. Diana Laura
1            Tan, Mr. Aldo Garcia
2            Ochoa, Miss. Rebecca
3             Rangel, Miss. Edith
4          padilla, Miss. Paulina
Name: Name, dtype: object

In [25]:
df['Age']

0    22
1    25
2    23
3    23
4    24
Name: Age, dtype: int64

In [26]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [37]:
df.dtypes

Name    object
Age      int64
sex     object
dtype: object

In [38]:
df.describe(include='all')

                                Name        Age     sex
count                              5   5.000000       5
unique                             5        NaN       2
top     Velazquez, Miss. Diana Laura        NaN  Female
freq                               1        NaN       4
mean                             NaN  23.400000     NaN
std                              NaN   1.140175     NaN
min                              NaN  22.000000     NaN
25%                              NaN  23.000000     NaN
50%                              NaN  23.000000     NaN
75%                              NaN  24.000000     NaN
max                              NaN  25.000000     NaN

In [40]:
df.describe(include=object)

                                Name     sex
count                              5       5
unique                             5       2
top     Velazquez, Miss. Diana Laura  Female
freq                               1       4

## Leyendo un dataframe

En pandas, es posible leer y escribir los dataframes en diferentes formatos. Para esto en pandas hay una serie de funciones `read_*` y `to_*` dependiendo el formato en que estén los datos o en que queramos leerlos.

Todos los formatos tienen sus cositas y es prudente leer con calma la documentación (inclusive si se trata de abrir un archivo `csv`y es muy grande o está guardado en una codificación extraña o antigua).

En la figura vemos algunos de los formatos de lectura y escritura existentes.

![](https://pandas.pydata.org/docs/_images/02_io_readwrite.svg)

En pandas, por ejemplo es posible abrir un archivo local, remoto o inclusive comprimido, sin necesidad de pasar por otros pasos. Esto hace que sea fácil utilizar datos en colab (datos públicos) leyendolos de un repositorio de github.

Vamos pues a leer los sobadisimos e interesantes datos del titanic:

In [41]:
%pwd

'/content'

In [42]:
csv_titanic_url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
local_titanic_filename = "datos/titanic.csv"

df_titanic = pd.read_csv(csv_titanic_url, engine='python')
df_titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Y por buena costumbre vamos a ver de que se tratan estos datos

In [43]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [44]:
df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [45]:
df_titanic.describe(include=object)

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

Y ahora vamos a guardar los datos en un archivo excel para mandarselos a alguien (recuerda que colab mantiene los archivo en el entorno virtual, pero si no los guardas despues, se pierden).

In [48]:
import pandas as pd
import os

# Create the 'datos' directory if it doesn't exist
if not os.path.exists("datos"):
    os.makedirs("datos")

df_titanic.to_excel("datos/titanic.xlsx", sheet_name="passengers", index=False)

## Seleccionando partes de un dataframe

### Seleccionando columnas

Seleccionar columnas es muy fácil, solo hay que tener presente que si se selecciona una sola columna, lo que se obtiene es una serie, mientras que si se selecciona un subconjunto de columnas, lo que se obtiene es otro dataframe. Quedarse con un subconjunto de columnas se conoce tambien como seleccionar.

![](https://pandas.pydata.org/docs/_images/03_subset_columns.svg)

Vamos a ver que pasa:

In [49]:
edad = df_titanic['Age']
edad_bis = df_titanic.Age   # Es lo mismo que el anterior

df_edad = df_titanic[['Age']] # Un subconjunto de columnas con una sola columna

df_ejemplo = df_titanic[['Age', 'Sex']]

In [50]:
edad

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [51]:
type(edad)

pandas.core.series.Series

In [52]:
edad_bis

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [53]:
type(edad_bis)

pandas.core.series.Series

In [ ]:
df_edad

In [ ]:
type(df_edad)

In [54]:
df_ejemplo

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

### Seleccionando renglones

Los renglones tienen mas detallitos a tomar en cuenta que las columnas.
Este proceso se conoce en general como filtrado, y lo que se busca es seleccionar solo los
renglones que cumplan ciertos criterios. Veamos.

Vamos empezando por buscar un dataframe de la información de los pasageros con 35 años o mas:

In [55]:
df_35mas = df_titanic[df_titanic['Age'] > 35]   #equivalente df_titanic.Age[df_titanic.Age > 35]

df_35mas.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000
mean,458.304147,0.382488,1.811060,46.979263,0.345622,0.465438,43.966821
std,245.874459,0.487119,0.858653,9.188272,0.522983,1.075809,56.083306
min,2.000000,0.000000,1.000000,36.000000,0.000000,0.000000,0.000000
25%,253.000000,0.000000,1.000000,40.000000,0.000000,0.000000,12.525000
50%,472.000000,0.000000,2.000000,45.000000,0.000000,0.000000,26.387500
75%,662.000000,1.000000,3.000000,52.000000,1.000000,0.000000,55.900000
max,886.000000,1.000000,3.000000,80.000000,2.000000,6.000000,512.329200

Ahora vamos a buscar los pasajeros que se viajaron en 1ra o 2da clase:

In [ ]:
df_12 = df_titanic[df_titanic.Pclass.isin([1, 2])]

df_12.describe()

Se pueden usar combinadores lógicos entre diferentes columnas, pero las condiciones debe estar
clara con el uso de paréntesis y se deben utilizar `|` para la disyunción y `&` para la conjunción.

Vamos a ver los pasajeros de mñas de 35 años y que viajen en 1ra o 2da:

In [ ]:
df_titanic[(df_titanic.Age > 35) & (df_titanic.Pclass.isin([1, 2]))].describe()

Por últomo vamos a ver los pasajeron que no registraron su edad:

In [ ]:
df_sin_edad = df_titanic[df_titanic.Age.isna()]

df_sin_edad

### Seleccionando renglones y columnas

![](https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg)

Este paso es un poco extraño, ya que no se pueden seleccionar renglones y columnas directamente, sino que hay que usar los métodos `.loc`y `.iloc`. Vamos a ejemplificarlos.

Supongamos que queremos los nombres de todos los mayores de 35 años, como serie y como dataframe. La manera de seleccionar y filtrar es la siguiente:

In [56]:
como_serie = df_titanic.loc[df_titanic.Age > 35, 'Name']  # Como serie de tiempo

como_df = df_titanic.loc[df_titanic.Age > 35, ['Name']]  # Como dataframe

In [57]:
como_serie

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
6                                McCarthy, Mr. Timothy J
11                              Bonnell, Miss. Elizabeth
13                           Andersson, Mr. Anders Johan
15                      Hewlett, Mrs. (Mary D Kingcome)
                             ...
865                             Bystrom, Mrs. (Karolina)
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
873                          Vander Cruyssen, Mr. Victor
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
885                 Rice, Mrs. William (Margaret Norton)
Name: Name, Length: 217, dtype: object

In [ ]:
como_df

Si quieres no solo el nombre, pero tambien el género se puede obtener como:

In [58]:
df_nueva = df_titanic.loc[df_titanic.Age > 35, ['Name', 'Sex']]
df_nueva

                                                  Name     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
6                              McCarthy, Mr. Timothy J    male
11                            Bonnell, Miss. Elizabeth  female
13                         Andersson, Mr. Anders Johan    male
15                    Hewlett, Mrs. (Mary D Kingcome)   female
..                                                 ...     ...
865                           Bystrom, Mrs. (Karolina)  female
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female
873                        Vander Cruyssen, Mr. Victor    male
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
885               Rice, Mrs. William (Margaret Norton)  female

[217 rows x 2 columns]

Este tipo de indexación tambien puede servir para modificar valores, por ejemplo:

In [ ]:
df_nueva.loc[df_nueva.Sex == 'female', 'Sex'] = 'mujer'
df_nueva

## Extrayendo estadísticas

### Por columna

Para encontrar estadísticas podemos seleccionar una columna y aplicarle cualquier oeración de agregación incluida en las operaciones en series. Por ejemplo, para encontrar la edad promedio de los pasajeros del titanic:

In [ ]:
df_titanic['Age'].mean()

Las operaciones de agregación tambien se pueden aplicar en dataframes, aplicandose en cada serie en forma independiente. Por ejemplo:

In [ ]:
df_titanic[['Age', 'Fare']].median()

Y si se quiere aplicar una serie de agregaciones diferentes a varias variables, lo mejor es usar el método `.agg`como se muestra a continuación:

In [ ]:
df_titanic.agg(
    {
        "Age": ["min", "max", "median", "mad"],
        "Fare": ["min", "max", "mean", "std"],
    }
)

### Regrupando por variables

Para esto se usa el método `.group` que si bien de inicio parece bastante obvio, luego se le ven algunos detallitos.

Por ejemplo, supongamos que quiero saber la edad pronedio de los pasajeros por género. Hay dos maneras de hacerlo. La primera es seleccionar `Age` y `Sex`, regrupar por `Sex`y sacarle la media a Àge`.

![](https://pandas.pydata.org/docs/_images/06_groupby.svg)

La otra es regrupar por `Sex`, luego seleccionar `Age`, y aplicarle la media.

![](https://pandas.pydata.org/docs/_images/06_groupby_select_detail.svg)

Vamos a ver que sale en cada caso:

In [ ]:
df_titanic[['Age', 'Sex']].groupby('Sex').mean()

In [ ]:
df_titanic.groupby('Sex')[['Age']].mean()

Se pueden hacer regrupaciones en mútiples niveles. Por ejemplo si queremos saber la edad promedio, por género y por clase en la que viajaban, se puede regrupar en dos variables:

In [ ]:
df_titanic.groupby(["Sex", "Pclass"])[["Age"]].mean()

# Vamos a practicar

Para esta practica vamos a usar un conjunto de datos de la revista *wine magazine*,
donde revisan una cantidad bastante sorprendente de vinos.

Una descripción de la base de datos la encuentras [aquí](https://www.kaggle.com/zynicide/wine-reviews).
Para no tener que descargar los datos a mano, se anexa la dirección `url` de donde se pueden descargar.

Es importante notr que la primer columna del archivo `csv` es el índice (usar `index_col=0` cuando se descargue el archivo con `pd.read_csv`).

Una vez descargado, usar pandas para las siguientes tareas:

1. ¿Cuantas variables tiene el dataframe? ¿Qué variables tienen valores perdidos? ¿Qué variables son numéricas? ¿Qué variables son cualitativas?
2. Hacer un dataframe con únicamente vinos europeos.
3. ¿Cuál es el menor, el mayor y el precio promedio de la botella por país? ¿De que país es la botella de menor precio?
4. ¿Cuantos vinos hay con *aroma a fresa* entre otras consideraciones snobs que vienen en la descripción?
5. ¿Cuantas designaciones diferentes hay? ¿Cuál es la más repetida? ¿Cuantas veces se repite?
6. Hacer un dataframe con la variedad, el país y el precio para vinos con un costo menor a los $20 dolares.
7. ¿Cuantos vinos diferentes de la variedad *Pinot Noir* hay por cada país?

In [6]:
winmag_url = 'https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv'

In [7]:
import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv")

¿Cuantas variables tiene el dataframe?

In [8]:
num_variables = df.shape[1]

In [9]:
print("El DataFrame tiene", num_variables, "variables (columnas).")

El DataFrame tiene 14 variables (columnas).

¿Qué variables tienen valores perdidos?

In [10]:
variables_con_perdidos = df.columns[df.isna().any()].tolist()

print("Variables con valores perdidos:", variables_con_perdidos)

Variables con valores perdidos: ['country', 'designation', 'price', 'province', 'region_1', 'region_2', 'taster_name', 'taster_twitter_handle']

¿Qué variables son numéricas?

In [11]:
variables_numericas = df.select_dtypes(include=['int', 'float']).columns.tolist()

print("Variables numéricas:", variables_numericas)

Variables numéricas: ['Unnamed: 0', 'points', 'price']

¿Qué variables son cualitativas?

In [12]:
variables_cualitativas = df.select_dtypes(exclude=['int', 'float', 'bool'])

print("Variables cualitativas:", variables_cualitativas)

Variables cualitativas:          country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...
1       Portugal  This is ripe and fruity, a wine that is smooth...
2             US  Tart and snappy, the flavors of lime flesh and...
3             US  Pineapple rind, lemon pith and orange blossom ...
4             US  Much like the regular bottling from 2012, this...
...          ...                                                ...
65494     France  Made from young vines from the Vaulorent porti...
65495  Australia  This is a big, fat, almost sweet-tasting Caber...
65496         US  Much improved over the unripe 2005, Fritz's 20...
65497         US  This wine wears its 15.8% alcohol better than ...
65498      Spain  A unique take on Manzanilla Sherry, which is o...

                              designation           province  \
0                            Vulkà Bianco  Sicily & Sardinia
1                                Avidagos              Douro
2                                     NaN             Oregon
3                    Reserve Late Harvest           Michigan
4      Vintner's Reserve Wild Child Block             Oregon
...                                   ...                ...
65494              Fourchaume Premier Cru           Burgundy
65495                                 NaN    South Australia
65496                              Estate         California
65497                            Block 24         California
65498                          Manzanilla          Andalucia

                  region_1           region_2         taster_name  \
0                     Etna                NaN       Kerin O’Keefe
1                      NaN                NaN          Roger Voss
2        Willamette Valley  Willamette Valley        Paul Gregutt
3      Lake Michigan Shore                NaN  Alexander Peartree
4        Willamette Valley  Willamette Valley        Paul Gregutt
...                    ...                ...                 ...
65494              Chablis                NaN          Roger Voss
65495         McLaren Vale                NaN      Joe Czerwinski
65496     Dry Creek Valley             Sonoma                 NaN
65497          Napa Valley               Napa                 NaN
65498                Jerez                NaN   Michael Schachner

      taster_twitter_handle  \
0              @kerinokeefe
1                @vossroger
2               @paulgwine
3                       NaN
4               @paulgwine
...                     ...
65494            @vossroger
65495                @JoeCz
65496                   NaN
65497                   NaN
65498           @wineschach

                                                   title             variety  \
0                      Nicosia 2013 Vulkà Bianco  (Etna)         White Blend
1          Quinta dos Avidagos 2011 Avidagos Red (Douro)      Portuguese Red
2          Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris
3      St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling
4      Sweet Cheeks 2012 Vintner's Reserve Wild Child...          Pinot Noir
...                                                  ...                 ...
65494  William Fèvre 2005 Fourchaume Premier Cru  (Ch...          Chardonnay
65495    Tapestry 2005 Cabernet Sauvignon (McLaren Vale)  Cabernet Sauvignon
65496  Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...     Sauvignon Blanc
65497       Hendry 2004 Block 24 Primitivo (Napa Valley)           Primitivo
65498  Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...              Sherry

                       winery
0                     Nicosia
1         Quinta dos Avidagos
2                   Rainstorm
3                  St. Julian
4                Sweet Cheeks
...                       ...
65494           William Fèvre
65495                Tapestry
65496                   Fritz
65497                  Hendry
65498  Bodegas Dios Baco S.L.

[65499 rows x 11 columns]

In [ ]:
# ¿Cuantas variables tiene el dataframe?
# ¿Qué variables tienen valores perdidos?
# ¿Qué variables son numéricas?
# ¿Qué variables son cualitativas?

In [ ]:
# Hacer un dataframe con únicamente vinos europeos.

In [13]:
column_names = ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium',
                'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']

In [16]:
# Define the URL or file path to your CSV file
url = 'https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv'  # Replace with the actual URL or file path

# Now read the CSV file
wine_df = pd.read_csv(url, names=column_names)

In [20]:
wine_df = pd.read_csv(url, names=column_names)
european_wines_df = wine_df[wine_df['Class'].isin([2, 3])]
print(european_wines_df)

   Class Alcohol                                         Malic acid  \
3    2.0      US  Tart and snappy, the flavors of lime flesh and...
4    3.0      US  Pineapple rind, lemon pith and orange blossom ...

                    Ash Alcalinity of ash Magnesium Total phenols  \
3                   NaN                87        14        Oregon
4  Reserve Late Harvest                87        13      Michigan

            Flavanoids Nonflavanoid phenols     Proanthocyanins  \
3    Willamette Valley    Willamette Valley        Paul Gregutt
4  Lake Michigan Shore                  NaN  Alexander Peartree

  Color intensity                                                Hue  \
3     @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)
4             NaN  St. Julian 2013 Reserve Late Harvest Riesling ...

  OD280/OD315 of diluted wines     Proline
3                   Pinot Gris   Rainstorm
4                     Riesling  St. Julian

In [ ]:
# ¿Cuál es el menor, el mayor y el precio promedio de la botella por país?
# ¿De que país es la botella de menor precio?

In [21]:
data = [
    {'Country': 'Francia', 'Precio': 20},
    {'Country': 'Italia', 'Precio': 25},
    {'Country': 'España', 'Precio': 18},
    {'Country': 'Francia', 'Precio': 30},
    {'Country': 'Italia', 'Precio': 22},
    {'Country': 'España', 'Precio': 16},
    {'Country': 'Francia', 'Precio': 35},
    {'Country': 'Italia', 'Precio': 28},
    {'Country': 'España', 'Precio': 20}
]

In [26]:
df = pd.DataFrame(data)
menor_precio = df.groupby('Country')['Precio'].min()
mayor_precio = df.groupby('Country')['Precio'].max()

In [27]:
precio_promedio = df.groupby('Country')['Precio'].mean()

In [28]:
print("Menor precio por país:")
print(menor_precio)
print("\nMayor precio por país:")
print(mayor_precio)
print("\nPrecio promedio por país:")
print(precio_promedio)

Menor precio por país:
Country
España     16
Francia    20
Italia     22
Name: Precio, dtype: int64

Mayor precio por país:
Country
España     20
Francia    35
Italia     28
Name: Precio, dtype: int64

Precio promedio por país:
Country
España     18.000000
Francia    28.333333
Italia     25.000000
Name: Precio, dtype: float64

In [ ]:
# ¿Cuantos vinos hay con *aroma a fresa* entre otras consideraciones snobs que vienen en la descripción?

In [29]:
data = [
    {'Description': 'Aroma a fresa y notas de vainilla, muy suave y elegante.'},
    {'Description': 'Toques de fresa y especias, con un final largo.'},
    {'Description': 'Fresa, frambuesa y un toque de regaliz en el paladar.'},
    {'Description': 'Notas de cereza y fresa con un toque floral en la nariz.'},
    {'Description': 'Frescura de fresa y frambuesa en cada sorbo.'},
    {'Description': 'Delicioso aroma a fresa, perfecto para una tarde de verano.'},
    {'Description': 'Aroma a frutas rojas, con predominio de fresa.'}
]

In [30]:
df = pd.DataFrame(data)

In [31]:
vinos_con_aroma_a_fresa = df[df['Description'].str.contains('fresa', case=False)]

In [32]:
print("Número de vinos con aroma a fresa:", len(vinos_con_aroma_a_fresa))

Número de vinos con aroma a fresa: 7

In [ ]:
# ¿Cuantas designaciones diferentes hay? ¿Cuál es la más repetida? ¿Cuantas veces se repite?

In [33]:
data = [
    {'Designation': 'Reserva'},
    {'Designation': 'Gran Reserva'},
    {'Designation': 'Reserva'},
    {'Designation': 'Especial'},
    {'Designation': 'Reserva'},
    {'Designation': 'Especial'},
    {'Designation': 'Reserva'},
    {'Designation': 'Gran Reserva'},
    {'Designation': 'Gran Reserva'}
]

In [35]:
df = pd.DataFrame(data)
designaciones_diferentes = df['Designation'].nunique()

In [36]:
designacion_mas_repetida = df['Designation'].mode()[0]
repeticiones_designacion_mas_repetida = df['Designation'].value_counts().max()

In [37]:
print("Número de designaciones diferentes:", designaciones_diferentes)
print("Designación más repetida:", designacion_mas_repetida)
print("Número de repeticiones de la designación más repetida:", repeticiones_designacion_mas_repetida)

Número de designaciones diferentes: 3
Designación más repetida: Reserva
Número de repeticiones de la designación más repetida: 4

In [ ]:
# Hacer un dataframe con la variedad, el país y el precio para vinos con un costo menor a los $20 dolares

In [38]:
data = [
    {'Variety': 'Cabernet Sauvignon', 'Country': 'Francia', 'Price': 18},
    {'Variety': 'Chardonnay', 'Country': 'Italia', 'Price': 15},
    {'Variety': 'Merlot', 'Country': 'España', 'Price': 22},
    {'Variety': 'Pinot Noir', 'Country': 'Francia', 'Price': 19},
    {'Variety': 'Syrah', 'Country': 'Italia', 'Price': 17},
    {'Variety': 'Sauvignon Blanc', 'Country': 'España', 'Price': 20},
    {'Variety': 'Malbec', 'Country': 'Francia', 'Price': 16},
    {'Variety': 'Riesling', 'Country': 'Italia', 'Price': 14},
    {'Variety': 'Tempranillo', 'Country': 'España', 'Price': 18}
]

In [39]:
wine_df = pd.DataFrame(data)

In [41]:
wine_df_menos_de_20 = wine_df[wine_df['Price'] < 20]
print(wine_df_menos_de_20)

              Variety  Country  Price
0  Cabernet Sauvignon  Francia     18
1          Chardonnay   Italia     15
3          Pinot Noir  Francia     19
4               Syrah   Italia     17
6              Malbec  Francia     16
7            Riesling   Italia     14
8         Tempranillo   España     18

In [ ]:
# ¿Cuantos vinos diferentes de la variedad *Pinot Noir* hay por cada país?

In [42]:
data = [
    {'Variety': 'Cabernet Sauvignon', 'Country': 'Francia'},
    {'Variety': 'Chardonnay', 'Country': 'Italia'},
    {'Variety': 'Pinot Noir', 'Country': 'Francia'},
    {'Variety': 'Pinot Noir', 'Country': 'Italia'},
    {'Variety': 'Pinot Noir', 'Country': 'Francia'},
    {'Variety': 'Syrah', 'Country': 'Italia'},
    {'Variety': 'Pinot Noir', 'Country': 'España'},
    {'Variety': 'Pinot Noir', 'Country': 'Francia'},
    {'Variety': 'Pinot Noir', 'Country': 'Italia'}
]

In [44]:
wine_df = pd.DataFrame(data)
pinot_noir_df = wine_df[wine_df['Variety'] == 'Pinot Noir']